### ISSUE TITLE
Composition of no-op replacements produces incorrect (or confusing?) alignment

### ISSUE THREAD

**Issue by maxhgerlach** [microsoft/bistring#43]
```
>>> from bistring import bistr
>>> b = bistr("abc")
>>> b1 = b.replace("bc", "bc")
>>> b2 = b1.replace("ab", "ab")
>>> b2
bistr('abc', 'abc', Alignment([(0, 0), (1, 2), (3, 3)]))
>>> b2[:2].original
'a'
```
Both individual replacements effectively don't change the contents of the original string. I think `b2[:2].original` "should" return `'abc'` here. This would probably be achieved with a coarser composed alignment `Alignment([(0, 0), (3, 3)])`.

**Comment by tavianator** [comment]
Ultimately this comes down to `Alignment.compose()` behaving strangely when the two alignments don't "line up."  In this case we have

```
>>> a1 = Alignment([(0, 0), (1, 1), (3, 3)])
>>> a2 = Alignment([(0, 0), (2, 2), (3, 3)])
>>> a = a1.compose(a2)
>>> a
Alignment([(0, 0), (1, 2), (3, 3)])
>>> a.original_bounds(0, 2)
(0, 1)
>>> a1.original_bounds(a2.original_bounds(0, 2))
(0, 3)
```

Visually it looks lilke

```
| |  |
| |  |
       .compose
|  | |
|  | |
           ↓
| |  |
| \  |
|  | |
```

You could argue that since (1, 1) and (2, 2) don't line up, we should just drop them and give

```
| |  |
| |  |
       .compose
|  | |
|  | |
           ↓
|    |
|    |
```

But the issue is with long alignments that don't "line up," that can lose a lot of precision:

```
|   |   |   |   |   |
|   |   |   |   |   |
                      .compose
| |   |   |   |   | |
| |   |   |   |   | |
                          ↓
|                   |
|                   |    ???
```

**Comment by maxhgerlach** [comment]
Thanks for the patch! I understand the problem about the potential loss of precision. We'll have to give this some thought and experiment with actual applications.
